server:
 port: ${PORT:8077}

#PostgreSQL
spring:
  config:
    import: optional:file:.env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#gemini key
gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}